version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      #These variables, used in conjunction, create a new user and set that user's password. This user is created in the admin authentication database and given the role of root, which is a "superuser" role.
      MONGO_INITDB_DATABASE: the_database
      #tell MongoDB to create a database with that name. 
    volumes:
    #bind mount the init file
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js 
      #bind mount the db itself so local copy matches
      - ./mongo_data:/data/db
  redis:
    image: redis
    ports:
      - 6379:6379