version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - 3456:27017 # 3456 exposed on host machine, but container is listening to 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      #These variables, used in conjunction, create a new user and set that user's password. This user is created in the admin authentication database and given the role of root, which is a "superuser" role.
      MONGO_INITDB_DATABASE: the_database
      #tell MongoDB to create a database with that name. 
    volumes:
      #bind mount the init file
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js 
      #bind mount the db itself so local copy matches
      - ./mongo_data:/data/db
  redis:
    image: redis
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes'] # Overwrite the CMD
    volumes: # Declare the volume for persiting data
      - ./redis_data:/data
  server:
    image: todo-backend-dev
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mongo
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database # @localhost:3456 vs @mongo:27017 .... server service connects to mongo service @ container port 27017